// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2kfFs_OZ-XH2hnOyg5mVpr_svuAd12Z8',
    appId: '1:493159780658:web:87aad57a5b95eb20e3c72b',
    messagingSenderId: '493159780658',
    projectId: 'tourist-28c83',
    authDomain: 'tourist-28c83.firebaseapp.com',
    storageBucket: 'tourist-28c83.appspot.com',
    measurementId: 'G-2TVCL1L7S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG7ND-xy1NbLha-C37hXzXgSoyx5ufHEU',
    appId: '1:493159780658:android:f2194e3f0e4a7c3ce3c72b',
    messagingSenderId: '493159780658',
    projectId: 'tourist-28c83',
    storageBucket: 'tourist-28c83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCv6O9pFVjCQqpPbTWOQ_xR8LQ7Av56TM',
    appId: '1:493159780658:ios:b9c87dc7dd5b6be3e3c72b',
    messagingSenderId: '493159780658',
    projectId: 'tourist-28c83',
    storageBucket: 'tourist-28c83.appspot.com',
    iosBundleId: 'com.example.tourist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCv6O9pFVjCQqpPbTWOQ_xR8LQ7Av56TM',
    appId: '1:493159780658:ios:d0fc03eeb08a0cabe3c72b',
    messagingSenderId: '493159780658',
    projectId: 'tourist-28c83',
    storageBucket: 'tourist-28c83.appspot.com',
    iosBundleId: 'com.example.tourist.RunnerTests',
  );
}
